mods = '''BaseHTTPServer.py
ConfigParser.py
SocketServer.py
StringIO.py
UserDict.py
_LWPCookieJar.py
_MozillaCookieJar.py
__future__.py
_abcoll.py
_threading_local.py
_weakrefset.py
abc.py
atexit.py
base64.py
bdb.py
bisect.py
calendar.py
cmd.py
codecs.py
collections.py
cookielib.py
copy.py
copy_reg.py
ctypes\__init__.py
ctypes\_endian.py
difflib.py
dis.py
doctest.py
dummy_thread.py
dummy_threading.py
email\__init__.py
email\_parseaddr.py
email\base64mime.py
email\charset.py
email\encoders.py
email\errors.py
email\feedparser.py
email\generator.py
email\header.py
email\iterators.py
email\message.py
email\mime\__init__.py
email\parser.py
email\quoprimime.py
email\utils.py
encodings\__init__.py
encodings\aliases.py
fnmatch.py
ftplib.py
functools.py
genericpath.py
getopt.py
getpass.py
gettext.py
glob.py
gzip.py
hashlib.py
heapq.py
hmac.py
httplib.py
site-packages\httplib2\__init__.py
site-packages\httplib2\iri2uri.py
site-packages\httplib2\socks.py
inspect.py
io.py
keyword.py
linecache.py
locale.py
logging\__init__.py
logging\handlers.py
md5.py
mimetools.py
mimetypes.py
ntpath.py
nturl2path.py
opcode.py
optparse.py
os.py
os2emxpath.py
pdb.py
pickle.py
posixpath.py
pprint.py
quopri.py
random.py
re.py
repr.py
rfc822.py
sha.py
shlex.py
smtplib.py
socket.py
sre_compile.py
sre_constants.py
sre_parse.py
ssl.py
stat.py
string.py
struct.py
subprocess.py
tempfile.py
textwrap.py
threading.py
token.py
tokenize.py
traceback.py
types.py
urllib.py
urllib2.py
urlparse.py
uu.py
warnings.py
weakref.py
site-packages\win32\lib\win32con.py
site-packages\win32\lib\win32evtlogutil.py
site-packages\win32\lib\winerror.py
xml\__init__.py
xml\etree\__init__.py
xml\etree\ElementPath.py
xml\etree\ElementTree.py
xml\parsers\__init__.py
xml\parsers\expat.py'''
libpath = r'D:\Dev\Python\Python27\Lib'
import os
if not os.path.exists('python27'):
    os.mkdir('python27')
for m in mods.split('\n'):
    os.system('xcopy /y %s\%s python27\%s' % (libpath, m, m))
